-- Must match the ERD in ARCHITECTURE.md (generated by /arch from this file).
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE token_sets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  tokens jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE primitives (
  name text PRIMARY KEY,
  prop_schema jsonb NOT NULL,
  schema_version int NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE design_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id),
  title text NOT NULL DEFAULT 'Untitled',
  current_doc jsonb NOT NULL,
  current_version int NOT NULL DEFAULT 0,
  token_set_id uuid NOT NULL REFERENCES token_sets(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id),
  document_id uuid NOT NULL REFERENCES design_documents(id),
  stt_provider text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE utterances (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id),
  seq int NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  finalized_at timestamptz,
  final_text text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, seq)
);

CREATE TABLE transcript_segments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  utterance_id uuid NOT NULL REFERENCES utterances(id),
  is_final boolean NOT NULL,
  text text NOT NULL,
  confidence real,
  t_ms int NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE intents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  utterance_id uuid NOT NULL REFERENCES utterances(id),
  intent jsonb NOT NULL,
  delta_score real NOT NULL,
  committed boolean NOT NULL DEFAULT false,
  path text CHECK (path IN ('lexicon','haiku','sonnet','fused')),
  t_ms int NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE generation_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  intent_id uuid UNIQUE REFERENCES intents(id),
  session_id uuid NOT NULL REFERENCES sessions(id),
  model text NOT NULL,
  status text NOT NULL CHECK (status IN ('running','done','aborted','failed')),
  input_tokens int,
  output_tokens int,
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE design_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL REFERENCES design_documents(id),
  version int NOT NULL,
  doc jsonb NOT NULL,
  job_id uuid UNIQUE REFERENCES generation_jobs(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (document_id, version)
);

CREATE TABLE patch_ops (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL REFERENCES generation_jobs(id),
  seq int NOT NULL,
  op text NOT NULL CHECK (op IN ('add','remove','replace','move','copy','test')),
  path text NOT NULL,
  value jsonb,
  primitive text REFERENCES primitives(name),
  applied boolean NOT NULL DEFAULT false,
  t_ms int NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (job_id, seq)
);

CREATE TABLE exports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version_id uuid NOT NULL REFERENCES design_versions(id),
  format text NOT NULL CHECK (format IN ('react','html','png','url')),
  uri text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE latency_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid REFERENCES generation_jobs(id),
  utterance_id uuid REFERENCES utterances(id),
  stage text NOT NULL,
  t_ms int NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (job_id IS NOT NULL OR utterance_id IS NOT NULL)
);

CREATE INDEX ON transcript_segments (utterance_id, t_ms);

CREATE INDEX ON intents (utterance_id, t_ms);

CREATE INDEX ON patch_ops (job_id, seq);

CREATE INDEX ON latency_events (job_id, stage);

CREATE INDEX ON latency_events (utterance_id, stage);
